# Generated by Django 5.1.2 on 2024-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hard_skills',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Django', 'Django'), ('Flutter', 'Flutter')], max_length=50, null=True),
        ),
    ]
