# Generated by Django 5.1.2 on 2024-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_profile_hard_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hard_skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
