# Generated by Django 5.1 on 2024-08-27 22:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField(help_text='Descreva seu post aqui', max_length=750)),
                ('calendar', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricula', models.CharField(help_text='Entre com sua matrícula', max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('password', models.CharField(help_text='Entre com os seis primeiros dígitos do seu cpf', max_length=6)),
                ('user_name', models.CharField(max_length=30)),
                ('summary', models.TextField(help_text='Descreva seus conhecimentos aqui', max_length=750)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.project')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('matricula', models.CharField(help_text='Entre com sua matrícula', max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('password', models.CharField(help_text='Entre com os seis primeiros dígitos do seu cpf', max_length=6)),
                ('user_name', models.CharField(max_length=30)),
                ('summary', models.TextField(help_text='Descreva seus conhecimentos aqui', max_length=750)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.project')),
            ],
        ),
    ]
