# Generated by Django 5.1 on 2024-10-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_project_author_profile_project_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='teacher',
            new_name='author',
        ),
    ]
