# Generated by Django 5.1 on 2024-11-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_comment_author_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(help_text='Descreva seus conhecimentos aqui', max_length=500),
        ),
    ]
