# Generated by Django 5.1 on 2024-11-09 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_profile_profile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matricula',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
