# Generated by Django 5.1 on 2024-11-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_profile_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/'),
        ),
    ]
