# Generated by Django 5.1.2 on 2024-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_project_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
