# Generated by Django 5.1 on 2024-11-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(max_length=750),
        ),
    ]
