# Generated by Django 5.1.2 on 2024-11-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(max_length=750),
        ),
    ]
