# Generated by Django 5.1.2 on 2024-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hard_skills',
            field=models.CharField(blank=True, help_text='Liste suas hard skills separadas por vírgula', max_length=200, null=True),
        ),
    ]
