# Generated by Django 5.1 on 2024-11-28 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_skill_remove_profile_hard_skills_profile_hard_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='feed.profile'),
        ),
    ]
