# Generated by Django 5.1 on 2024-12-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aberto'), (False, 'Fechado')], default=True),
        ),
    ]
